version: '2'
services:
  mysql:
        image: mysql:8.0
        container_name: mysql_server
        command: --default-authentication-plugin=mysql_native_password
        volumes:
          - ./MySQL:/var/lib/mysql
        restart: unless-stopped
        environment:
          - MYSQL_ROOT_PASSWORD=secret
          - MYSQL_USER=mendez
          - MYSQL_PASSWORD=mendezdb
        ports:
          - "3306:3306"
        expose: 
          - "3306"
  apache-php:
    image: php:8.1-apache
    container_name: php_server
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/html/
    ports:
      - "80:80"
    depends_on:
      - mysql